# DO NOT EDIT!
# This file was automatically generated by "generate_id_constants_from_stableid.py"

__all__ = ["unit_typeid", "ability_id", "upgrade_id", "buff_id", "effect_id"]
from .unit_typeid import UnitTypeId
from .ability_id import AbilityId
from .upgrade_id import UpgradeId
from .buff_id import BuffId
from .effect_id import EffectId
